name: drift_flutter
publish_to: none
description: Fake "drift_flutter" package so that we can import it in snippets without depending on Flutter.

environment:
  sdk: ^3.0.0

dependencies:
  drift:
    path: ../../../drift
